In [4]:
#import the necessary libraries
from os import listdir
from os.path import isfile, join
from skimage.transform import resize
import numpy as np
import cv2 as cv
import pandas as pd
from sklearn import svm
from sklearn.metrics import classification_report,accuracy_score
from skimage.io import imread, imshow
from skimage.feature import hog
from skimage import exposure
import matplotlib.pyplot as plt
%matplotlib inline

import csv
from collections import defaultdict

mypath='UFPR-Periocular/periocularCropped/'
columns = defaultdict(list)
label = []
hog_images = []
hog_features = []

with open('UFPR-Periocular/imagesInfo_csv.csv', mode='r') as csv_file:
    csv_reader = csv.DictReader(csv_file)
    df = pd.read_csv(csv_file)
    image_file_name,age,gender = df.file_name,df.age,df.gender

    
    for i in range(1):
        image = cv.imread( join(mypath,image_file_name[i]) )
        img = cv.cvtColor(image ,cv.COLOR_RGB2BGR)
        
        print(img)
        
        resized_img = resize(img, (128,64)) 
        print(resized_img)
        
        fd, hog_image = hog(resized_img, orientations=9, pixels_per_cell=(8, 8), 
                        cells_per_block=(2, 2), visualize=True, multichannel=True)

[[[169 247 251]
  [113 182 189]
  [ 86 135 150]
  ...
  [165 162 145]
  [159 157 145]
  [162 159 150]]

 [[162 232 240]
  [113 177 187]
  [ 92 141 156]
  ...
  [162 160 145]
  [167 164 155]
  [161 158 151]]

 [[193 252 255]
  [125 181 196]
  [ 79 124 145]
  ...
  [157 159 145]
  [163 160 153]
  [163 160 155]]

 ...

 [[171 250 247]
  [177 253 251]
  [179 253 252]
  ...
  [173 156 146]
  [175 156 150]
  [181 162 156]]

 [[171 250 247]
  [176 252 250]
  [179 253 252]
  ...
  [173 156 146]
  [174 157 150]
  [180 163 156]]

 [[171 250 247]
  [176 252 250]
  [178 252 251]
  ...
  [173 156 146]
  [174 157 150]
  [180 163 156]]]
[[[0.41960784 0.62941176 0.68039216]
  [0.23235294 0.31764706 0.37647059]
  [0.10196078 0.17745098 0.18823529]
  ...
  [0.62352941 0.61078431 0.58235294]
  [0.59411765 0.59901961 0.55882353]
  [0.62647059 0.61862745 0.57156863]]

 [[0.46470588 0.65882353 0.7254902 ]
  [0.2127451  0.34411765 0.39313725]
  [0.08627451 0.16078431 0.17647059]
  ...
  [0.63333333 0.6147058